// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCorePr.Models;

public partial class CartBook
{
    public int Id { get; set; }

    public int BookId { get; set; }

    public int CartId { get; set; }

    public virtual Book Book { get; set; }

    public virtual Cart Cart { get; set; }
}