// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCorePr.Models;

public partial class Cart
{
    public int Id { get; set; }

    public int TotalItem { get; set; }

    public int TotalPrice { get; set; }

    public int? UserId { get; set; }

    public bool IsDeleted { get; set; } = false;

    public virtual ICollection<CartBook> CartBook { get; set; } = new List<CartBook>();

    public virtual Customer Customer { get; set; }
}