// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCorePr.Models;

public partial class Rent
{
    public int Id { get; set; }

    public int CustomerId { get; set; }

    public int BookId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime FinishDate { get; set; }

    public bool IsDeleted { get; set; } = false;

    public virtual Book Book { get; set; }

    public virtual Customer Customer { get; set; }
}